version: '3'
services:
  microservicio:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mysql:3306/api?useSSL=false&serverTimezone=UTC
      - spring.datasource.username=root
      - spring.datasource.password=Freya-100MTH
    depends_on:
      - mysql
    restart: always

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Freya-100MTH
      MYSQL_DATABASE: api
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: